# Generated by Django 5.1.5 on 2025-02-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile_first_name_profile_gender_profile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userselection',
            name='selected_time_periods',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.URLField(blank=True, default='/static/images/default-profile.png', null=True),
        ),
    ]
