# Generated by Django 5.1.5 on 2025-03-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_matter_youtube_links_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='youtube_links',
        ),
        migrations.AddField(
            model_name='matter',
            name='youtube_links',
            field=models.TextField(blank=True, null=True),
        ),
    ]
