# Generated by Django 5.1.5 on 2025-03-23 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_category_table_alter_education_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='interest',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='app_profile',
        ),
        migrations.AlterModelTable(
            name='userselection',
            table='app_userselection',
        ),
        migrations.DeleteModel(
            name='EducationResource',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
