# Generated by Django 5.1.5 on 2025-03-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_job_interest_alter_profile_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='interestid',
            field=models.IntegerField(default=0),
        ),
    ]
