# Generated by Django 5.1.5 on 2025-03-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_interest_interestid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(db_column='categoryid', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='education',
            name='id',
            field=models.AutoField(db_column='educationid', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='matter',
            name='id',
            field=models.AutoField(db_column='matterid', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='roles',
            name='id',
            field=models.AutoField(db_column='roleid', primary_key=True, serialize=False),
        ),
    ]
