# Generated by Django 5.1.5 on 2025-03-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_interest_id_alter_interest_interestid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('video_url', models.URLField()),
            ],
            options={
                'db_table': 'youtube',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='interest',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='matter',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='userselection',
            options={'managed': False},
        ),
    ]
